### ISSUE TITLE
rename config.js to Config.js or change the require string

### ISSUE THREAD

**Issue by e-tip** [tam5/laravel-materialize#1]
Hi,
i'm just trying to install and use this package but when i execute gulp i get 
Error: Cannot find module '../config'
in these files
node_modules/laravel-materialize/tasks/sass.js
node_modules/laravel-materialize/tasks/images.js
node_modules/laravel-materialize/tasks/scripts.js
there's a line 
var Config = require('../config'); that should be var Config = require('../Config'); in systems that have case sensitive filesystems

**Comment by tam5** [comment]
fixed
