### ISSUE TITLE
untar error on windows

### ISSUE THREAD

**Issue by RobWJacob** [tam5/laravel-materialize#3]
i got an untar error when i install it on windows 10
i removed manualy the ```Icon_``` File from the package.tgz, and the install worked
i can't see this File on the github repro, maybe some mac osx thing?

**Comment by tam5** [comment]
The icon file for Mac is already in the gitignore, but I will try to test this out a little later tonight

**Comment by tam5** [comment]
I tested on windows and I can confirm i got the error you mentioned. I'm looking into it

**Comment by tam5** [comment]
Fixed with v1.0.9
