### ISSUE TITLE
laravel 5.3 + vuejs 2.0.1 component error

### ISSUE THREAD

**Issue by RobWJacob** [tam5/laravel-materialize#4]
i install a fresh laravel 5.3 with vuejs2

when i add `.materialize()` to my gulpfile.js

```
const elixir = require('laravel-elixir');

require('laravel-materialize');
require('laravel-elixir-vue-2');

elixir(mix => {
    mix.sass('app.scss')
        .materialize()
        .webpack('app.js');
});
```

i can not use vue components any more.

i got error: `vue.js [Vue warn]: Failed to mount component: template or render function not defined. (found in component <example>)`

without `.materialize()` it works as planned

when `.materialize()` is in the gulpfile.js, the generated app.js includes the materialize.js code but not my vue component code. but the main vuejs2 code is also in there, and it generates a seperate materialize.js file!

without `.materialize()` the vue component gets generated as planned.

**Comment by tam5** [comment]
https://github.com/vuejs/laravel-elixir-vue-2/issues/10

**Comment by nothingalike** [comment]
Im having the same issue
