### ISSUE TITLE
No gulpfile anymore

### ISSUE THREAD

**Issue by chwzr** [tam5/laravel-materialize#6]
How to add this in newer Laravel versions?

there is no central gulpfile.js anymore.

How to install this now?

**Comment by tam5** [comment]
Hi @chwzr, thanks for your interest.

As of Laravel 5.4, the build process for assets has been migrated from using Laravel Elixir which is based on Gulp to using Laravel Mix which is based on web pack, thus currently this package will only work for versions < 5.4.

If there is interest in continuing this project we can certainly create a new version that is compatible with Laravel Mix.

**Comment by chwzr** [comment]
Thanks for the quick information, i am using a older Version of laravel nö
and its working great.please See this as Interesse of a Version which works
with the newer versions :)

Am 11.05.2017 5:25 nachm. schrieb "Ari Miller" <notifications@github.com>:

**Comment by tam5** [comment]
I don't think there is enough interest in continuing this project to support newer versions of Laravel.
